[libc++abi] Fix unused function when building with LIBCXXABI_SILENT_TERMINATE
This fixes:
src/cxa_default_handlers.cpp:25:13: error: unused function 'demangling_terminate_handler' [-Werror,-Wunused-function]

Patch by Thomas Anderson!

Differential Revision: https://reviews.llvm.org/D42399

git-svn-id: http://llvm.org/svn/llvm-project/libcxxabi/trunk@323397 91177308-0d34-0410-b5e6-96231b3b80d8